# Generated by Django 3.2.12 on 2022-02-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stylesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for this stylesheet.', max_length=1023)),
                ('active', models.BooleanField(default=False, help_text='Whether or not this stylesheet ought to be linked to.')),
                ('href', models.CharField(help_text='The URL to the stylesheet.', max_length=1023)),
                ('static', models.BooleanField(default=False, help_text='Whether or not this stylesheet URL is relative .')),
                ('integrity', models.CharField(blank=True, default='', help_text='The Subresource Integrity (SRI) for this stylesheet (if applicable).', max_length=1023)),
                ('category', models.CharField(blank=True, default='', help_text="A category for this stylesheet (e.g. 'bootstrap').", max_length=1023)),
            ],
        ),
    ]
