# Generated by Django 4.2.17 on 2025-01-13 18:49

from django.db import migrations

from djangocms_themata.util import load_stylesheets

def load_fixture(apps, schema_editor):
    load_stylesheets()


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_themata", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
